language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=1.4
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  - pip install . --use-mirrors
script: ./test_project/manage.py test
